apiVersion: apps/v1
kind: Deployment
metadata:
  name: raas-redis-deployment
  namespace: default
  labels:
    app: raas-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raas-redis
  template:
    metadata:
      labels:
        app: raas-redis
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          ports:
            - containerPort: 6379
              name: redis-port
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "100m"