apiVersion: apps/v1
kind: Deployment
metadata:
  name: raas-worker-deployment
  namespace: default
  labels:
    app: raas-worker
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: raas-worker
  template:
    metadata:
      labels:
        app: raas-worker
    spec:
      containers:
        - name: worker-service
          image: projects-worker-service:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: raas-worker-config
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          envFrom:
            - configMapRef:
                name: raas-worker-config